name: linting, testing, building
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    runs-on: [ ubuntu-latest ]
    strategy:
      matrix:
        node-version: [ 16.14.2 ]
    steps:
      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: install modules
        run: npm install

      - name: build project prod version
        run: npm run build:prod

      - name: linting typescript
        run: npm run lint:ts

      - name: linting styles
        run: npm run lint:scss

      - name: unit testing
        run: npm run test:unit


