name: linting, testing, building
run-name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pipeline:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: install modules
        run: npm install

      - name: linting typescript
        run: npm run lint:ts
        if: always()

      - name: linting styles
        run: npm run lint:scss
        if: always()

      - name: build project prod version
        run: npm run build:prod
        if: always()

#      - name: unit testing
#        run: npm run test:unit
#        if: always()

      - name: build storybook
        run: npm run storybook:build
        if: always()

#      - name: screenshot testing
#        run: npm run test:ui:ci


